version: '2.1'

orbs:
  slack: circleci/slack@4.1

workflows:
  run-meson-units:
    jobs:
      - build
      - test

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: sudo apt-get -y install python3 python3-pip
      - run: sudo pip3 install meson
      - run: meson setup build
      - slack/notify:
          channel: software
          event: fail
          template: basic_fail_1
  test:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: sudo apt-get -y install python3 python3-pip
      - run: sudo pip3 install meson 
      - run: meson setup build
      - run: cd build
      - run: ninja
      - run: meson test
      - slack/notify:
          channel: software
          event: fail
          template: basic_fail_1